project:
  type: website

website:
  title: "Venu GVGK Raju"
  site-url: https://gvgk.in/

  open-graph: true
  twitter-card: true
  page-footer:
    border: true
    left: |
      Currently associated with [_Farm Hill Education Trust_](https://farmhill.in)
    right: 
      - icon: envelope-at
        href: mailto:venu.gvgk@gmail.com
      - icon: github
        href: https://github.com/venugvgk
      - icon: facebook
        href: https://www.facebook.com/venu.gvgk
      - icon: instagram
        href: https://instagram.com/venu.gvgk
  
  navbar:
      
      href: /index.qmd
      left:
       - text: Curriculum Vitae
         href: about.qmd
       - text: Blog
         href: blog/index.qmd
       - text: Books
         href: books/index.qmd
       - text: TIL
         href: til/index.qmd
       - text: TIR
         href: tir/index.qmd
       - text: On Education
         href: education/index.qmd

        
  

format:
  html: 
    theme: 
      - cosmo
      - styles.scss
    css: styles.css
    toc: true
    mainfont: Nunito, Mallanna



