project:
  type: website

website:
  title: "Venu GVGK Raju"
  open-graph: true
  twitter-card: true
  navbar:
      href: /index.qmd
      left:
       - text: Curriculum Vitae
         href: about.qmd
       - text: English Blog
         href: blog-english/index.qmd
       - text: Telugu Blog
         href: blog-telugu/index.qmd
        
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



